name: my-first-github-workflow

on: 
   push:
      branches:
         - main
   workflow_dispatch: 
# on:
#    schedule:
#      - cron: "*/5 * * * *"
   # workflow_dispatch: 
jobs:
   job1:
     name: First-Job
     runs-on: ubuntu-latest
     steps:
        - name: firstjob-first step
          run: echo "Hello World"
        - name: Check Directory
          run: |
            pwd
            ls -ltr
            hostname
        - name: Checkout
          uses: actions/checkout@v7
        - name: Check Directory
          run: |
            pwd
            ls -ltr
            hostname
