name: my-first-github-workflow

on: 
   push:
      branches:
         - main
jobs:
   job1:
     name: First-Job
     runs-on: ubuntu-latest
     steps:
        - name: firstjob-first step
          run: echo "Hello World"
   job2:
    needs: job1
    name: Second-Job
    runs-on: ubuntu-latest
    steps:
       - name: secondjob-firststep
         run: hostname
       - name: secondjob-secondstep
         run: |
            echo "Somethinggg"
            echo "Welcome to Github Actions"   
